ultralytics/yolov3

- utils/utils.py
Notes:
- The line `predictions.cpu()` was removed. Device location should be set outside function call.
- Using `cross_class_nms=True` takes place on the correct device (everything is done with torch operators rather than numpy) - but is very slow still (iterating all 30k bounding boxes) and should be fixed.
> Fixed NMS bug causing big CPU usage. 

- .gitignore
Expected behavior when I trying to run train.py using own dataset.
ignore several files that are related.
> Ignore private configuration files.

- train.py
- utils/utils.py
fix the multi gpu traning bug post in https://github.com/ultralytics/yolov3/issues/146
> fix the multi gpu training bug: zero map 

- utils/datasets.py
since the transformation is affine and not perspective it is more efficient to use the warpAffine function
> changed warpPerspective to warpAffine at line 380

- models.py
I found a not used variable "yolo_layer_count".
> cleanup- delete a variable "yolo_layer_count"

- train.py
I trained the model on my custom dataset. But I failed to get a good results when I load the weight file that has the lowest loss on test dataset. 
I thought that the loss used in YOLO is not the proper criteria for detection performance. So I changed the criteria from loss to mAP.
what do you think of this?
> changed the criteria for the best weight file

- train.py
Remove Unused Argument of parser : --var
> Remove Unused Argument of parser : --var

- models.py
Cleanup- edit for Readability
To increase readability, I modified the code order of inference process in YOLO layer.
> Cleanup- edit for Readability

- models.py
Replace EmptyLayer with nn.Sequential
> Replace EmptyLayer with nn.Sequential

- .dockerignore
Downloaded data is currently included in the docker build context. Thank you this wicked sick implementation. I humbly contribute this PR <3
> added coco/ to .dockerignore

- utils/utils.py
> return kmeans targets

- utils/datasets.py
> modify h range clip range in hsv augmentation

- utils/utils.py
Box coords may be negative or exceed borders.
> utils.clip_coords doesn't work as expected.

- train.py
revert value of gs back to 32(from 64)
> revert value of gs back to 32(from 64)

- train.py
Freeze layers that aren't of type YOLOLayer and that aren't the conv layers preceeding them
> Non-output layer freeze in train.py

- train.py
Fixed "Unexpected character after line continuation character"
> Fixed train.py SyntaxError

- test.py
changing target and prediction indices comments
> Edit comment in test.py

- .gitignore
This PR adds the W&B logging directory wandb/ to .gitignore.
> Ignore W&B logging dir wandb/

- utils/plots.py
From https://github.com/ultralytics/yolov5/pull/1566
> plot_images() scale bug fix

- utils/torch_utils.py
Fix for #1816. Torch CUDA synchronization is not attempted now on CUDA-enabled machines when --device cpu is requested.
> Update Torch CUDA Synchronize

- utils/loss.py
remove unused variable in def compute_loss function
> remove unused variable in def compute_loss function

- models/yolov3.yaml
Resolves https://github.com/ultralytics/yolov3/issues/1887#issuecomment-1041135181
> Fix yolov3.yaml remove extra bracket

- .github/workflows/ci-testing.yml
> Update ci-testing.yml remove macos-latest

- models/tf.py
> fix tflite converter bug for tiny models.

- export.py
> fix half bug.

- README.md
- README.zh-CN.md
> README link fixes

- README.md
- README.zh-CN.md
> Update social icons, add TikTok and remove Facebook

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
- .github/ISSUE_TEMPLATE/question.yml
> Update issue YAMLs

- .github/workflows/links.yml
Thank you 🙏 for your contribution to [Ultralytics](https://ultralytics.com) 🚀! Your effort in enhancing our repositories is greatly appreciated. To streamline the process and assist us in integrating your Pull Request (PR) effectively, please follow these steps:
1. **Check for Existing Contributions**: Before submitting, kindly explore existing PRs to ensure your contribution is unique and complementary.
2. **Link Related Issues**: If your PR addresses an open issue, please link it in your submission. This helps us better understand the context and impact of your contribution.
3. **Elaborate Your Changes**: Clearly articulate the purpose of your PR. Whether it's a bug fix or a new feature, a detailed description aids in a smoother integration process.
4. **Ultralytics Contributor License …
> Update links.yml to --scheme 'https'

- requirements.txt
Thank you 🙏 for your contribution to [Ultralytics](https://ultralytics.com) 🚀! Your effort in enhancing our repositories is greatly appreciated. To streamline the process and assist us in integrating your Pull Request (PR) effectively, please follow these steps:
1. **Check for Existing Contributions**: Before submitting, kindly explore existing PRs to ensure your contribution is unique and complementary.
2. **Link Related Issues**: If your PR addresses an open issue, please link it in your submission. This helps us better understand the context and impact of your contribution.
3. **Elaborate Your Changes**: Clearly articulate the purpose of your PR. Whether it's a bug fix or a new feature, a detailed description aids in a smoother integration process.
4. **Ultralytics Contributor License …
> Update requirements.txt to `numpy>=1.23.5`

- .github/workflows/links.yml
> Link checks SSL insecure robustness

- README.md
- export.py
- models/experimental.py
- utils/loggers/clearml/clearml_utils.py
Added Discord community badge to README and minor coding style improvements.
- A Discord badge has been included in the README to invite users to join the Ultralytics Discord community.
- Minor formatting changes in the `export.py` to improve the readability of the code comments.
- An additional whitespace line added in `models/experimental.py` for better code separation.
- An additional whitespace line added in `utils/loggers/clearml/clearml_utils.py` for code clarity.
- 🔗 The Discord badge provides easy access for users to connect with the community for support, discussions, and updates, enhancing user engagement.
- 📖 Code formatting changes contribute to cleaner and more maintainable code, although …
> Add Discord badge

- .github/workflows/ci-testing.yml
Improving efficiency in CI testing setup for the `yolov3` project.
- Simplified the installation process for dependencies, especially PyTorch and torchvision.
- Added retries for pip install to enhance the stability of the CI pipeline.
- **Efficiency**: Consolidating commands reduces complexity and potentially speeds up the CI process. 🚀
- **Stability**: Implementing retries for pip installation minimizes the chances of failure due to network issues or external repository problems, leading to a more reliable CI testing environment. 🛡️
Expect smoother CI runs with fewer interruptions, benefiting both developers and users who rely on stable builds.
> Add `pip install --retries 3` to CI to resolve transients

- requirements.txt
This PR updates the version requirement for the Ultralytics package in `requirements.txt`.
- Updated Ultralytics dependency version from `8.2.32` to `8.2.34`.
- **Purpose:** Ensures the project uses the latest improvements and bug fixes in the Ultralytics package.
- **Impact:** Users will benefit from enhanced features, better performance, and resolved issues by using the updated package version. 🚀🔧✨
> Update requirements.txt to `ultralytics>=8.2.34`

- README.md
- README.zh-CN.md
> Ultralytics Code Refactor https://ultralytics.com/actions

- .github/workflows/greetings.yml
- README.md
- README.zh-CN.md
This [Ultralytics](https://ultralytics.com) PR adds a new Discourse badge and also updates code to improve performance and readability. 🔄
- [Check Out Our Plans](https://www.ultralytics.com/plans) …
> Add Discourse at https://community.ultralytics.com

- README.md
- README.zh-CN.md
- classify/train.py
- classify/tutorial.ipynb
- data/GlobalWheat2020.yaml
- data/VisDrone.yaml
- data/coco.yaml
- data/coco128-seg.yaml
- data/coco128.yaml
- data/voc.yaml
- segment/tutorial.ipynb
- tutorial.ipynb
- utils/general.py
> Ultralytics Asset URL Update

- .github/workflows/format.yml
> YOLO Vision 2024 updates https://ultralytics.com/events/yolovision

- README.md
- export.py
- models/common.py
- models/experimental.py
- utils/activations.py
- utils/augmentations.py
- utils/callbacks.py
- utils/dataloaders.py
- utils/general.py
- utils/loggers/__init__.py
- utils/loggers/clearml/clearml_utils.py
- utils/loggers/wandb/wandb_utils.py
- utils/metrics.py
- utils/segment/augmentations.py
- utils/segment/general.py
- utils/triton.py
This PR refines the documentation by standardizing the formatting of various docstrings across several modules. 
- **Consistent Punctuation**: Added full stops and standardized the format of inline punctuation in docstrings.
- **Enhanced Readability**: Split longer docstrings into multiple lines to adhere to PEP 257.
- **Removed Redundant Blank Lines**: Elimination of unnecessary blank lines before and within docstrings, enhancing readability.
- **Improved Code Documentation**: Enhanced the clarity and consistency of in-code comments and docstrings.
- **Better Readability**: Easier for developers to understand and maintain the code.
- **Conformance to Standards**: Aligns documentation with Python's PEP …
> Apply Ruff Docstring reformat

- README.md
- classify/predict.py
- detect.py
- segment/predict.py
- utils/metrics.py
This PR implements code refactoring to enhance readability and maintainability by updating formatting methods across multiple files.
- Updated string formatting from `%gx%g` to `"{:g}x{:g}"` in `predict.py`, `detect.py`, and `segment/predict.py`.
- Modified metric plot precision/recall curve labeling from old format `%` to new format `f"{value}"` in `metrics.py`.
- **Improved Code Readability:** Makes the code more readable and consistent by using modern Python string formatting.
- **Enhanced Maintainability:** Simplifies future code adjustments and maintenance with a cleaner and more modern approach to string formatting.
- **No Functional Change:** These changes should not alter the functionality or …
> PyUpgrade 3.8 updates

- README.md
- README.zh-CN.md
README update emphasizing the Ultralytics HUB for training and deploying YOLO models.
- Updated README to feature Ultralytics HUB as a recommended tool for YOLO model training and deployment.
- Adjusted the order and emphasis of tutorial links to prioritize current strategies.
- **Enhanced Guidance**: Steering users towards Ultralytics HUB for a streamlined and efficient YOLO model management experience 🚀.
- **Improved Documentation**: Clarifies and organizes resources, making it easier for users to access relevant training and deployment tools, enhancing user experience and productivity.
> Update README.md with YOLO11 section

- README.md
- README.zh-CN.md
- utils/loggers/clearml/README.md
- utils/loggers/comet/README.md
Minor formatting update to the README for improved clarity and presentation.  
- Removed unnecessary blank lines in the README file.  
- 🛠️ Enhances the readability and structure of the README.  
- 📚 Ensures a cleaner and more professional presentation for users exploring YOLOv3.
> Bash code blocks reformat

- hubconf.py
- models/experimental.py
- pyproject.toml
- requirements.txt
- segment/train.py
- train.py
- utils/aws/resume.py
- utils/general.py
This update replaces direct use of PyTorch's `torch.load` with Ultralytics' custom `torch_load` function throughout the codebase, and bumps the minimum required Ultralytics version. 🚀
- Swapped all `torch.load` calls for `torch_load` from `ultralytics.utils.patches` in training, validation, and utility scripts.
- Updated dependency requirements to require `ultralytics>=8.2.64`.
- Minor import adjustments to support the new loading method.
- **Improved Compatibility:** Ensures consistent and robust model checkpoint loading, especially across different environments and PyTorch versions.
- **Better Error Handling:** The custom loader can handle edge cases or compatibility issues that the standard …
> FIx downstream impact by the replacement of `torch.load` in `ultralytics` package

- README.md
- README.zh-CN.md
README update: banner link now points to the YOLO Vision event page with tracking parameters—no code or model changes. 🔗✨
- Updated README banner URL from the general YOLO page to the YOLO Vision event page (with UTM tracking).
- No changes to code, models, APIs, or dependencies.
- Directs users to current YOLO Vision event info for timely updates and resources. 📅
- Adds analytics tracking to better understand traffic from GitHub. 📈
- Zero impact on installs, training, or inference—safe and backward-compatible. ✅
> Update banners redirect to https://www.ultralytics.com/events/yolovision
