data/get_coco_dataset.sh
This is presumably for unattended download on cloud systems, but the script should alert the user first. Automatically shutting down a system when you download some data shouldn't be default behaviour. It's also not in the original Darknet script (https://github.com/pjreddie/darknet/blob/master/scripts/get_coco_dataset.sh).
Alternatively run `get_coco_dataset.sh && sudo shutdown`.
=> Remove auto-shutdown from get coco script

models.py
I've found two issues while exporting the model to ONNX:
- L193 shape mismatch between the two addends
- At some places in `models.py`, the number of classes were hardcoded to 80
=> ONNX export for custom dataset

.gitignore, README.md, cfg/coco.data, detect.py, test.py, train.py, utils/gcp.sh, utils/utils.py
Aligned repository mAP computation to pycocotools, and improved mAP computation in general, which now exceeds darknet (using pycocotools to compare).
<i></i> | [ultralytics/yolov3](https://github.com/ultralytics/yolov3) with `pycocotools` | [darknet/yolov3](https://arxiv.org/abs/1804.02767) 
--- | --- | ---  
YOLOv3-320 | 51.8 | 51.5  
YOLOv3-416 | 55.4 | 55.3  
YOLOv3-608 | 58.2 | 57.9  
``` bash
sudo rm -rf yolov3 && git clone https://github.com/ultralytics/yolov3
sudo rm -rf cocoapi && git clone https://github.com/cocodataset/cocoapi && cd cocoapi/PythonAPI && make && cd ../.. && cp -r cocoapi/PythonAPI/pycocotools yolov3
cd yolov3
python3 test.py --save-json --conf-thres 0.001 --img-size 416
Namespace(batch_size=32, cfg='cfg/yolov3.cfg', conf_thres=0.001, data_cfg='cfg/coco.data', …
```
=> mAP Update

detect.py
When there are no detections, `detections` is `None`, causing the script to crash (can't call `len` on `None`).
=> Fix None bug in detect.py

train.py
A recent change made it such that train.py doesn't save models by default. This is counter-intuitive, and would make users train to completion only to realize everything is gone (exhibit A: myself 🙃).
=> Save model by default

detect.py
Resolves #243 
Added two more arguments for users to specify output file encoding and output file directory. Then I changed the default FourCC code which is known to work on Windows and Linux. It should also work on Mac, but I have not verified this personally but people a couple of StackOverflow threads suggest mpv4 works with QTkit.
=> Encoding of video output - Resolves Issue 243

train.py
Use `chkpt.get('training_results')` instead of `chkpt.get('training_results')` so if the dict doesn't contain this key it won't throw a `KeyError`
=> prevent failure when no training_results available

requirements.txt, train.py, utils/utils.py
Tensorboard support : 
- Scalars metrics of this repo (GIoU/XY, Width/Height, Confidence, Classification, Train loss, Precision, Recall, mAP, F1, Test loss GIoU, Test loss obj, Test loss cls)
- Adds the image this repo creates to check first train batch (not test, wasn't sure how to access the tensorboard writer in test) 
Tested it on Windows.
This works and doesn't break anything, but wasn't sure where to define the tensorboard writer and do my imports, you may want to move things arround. One thing to note is that the tensorboard writer needs to be defined under the `if name == main` guard or else Windows users will have many runs created (for each workers of the dataloader every epoch, see https://github.com/ultralytics/yolov3/issues/412)
=> Tensorboard support

train.py
When attempting to running this function in a multi-GPU environment I kept on getting a runtime issue. I was able to solve this problem by passing this keyword. I first found the solution here: 
https://github.com/pytorch/pytorch/issues/22436
and in the pytorch tutorial
'RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument find_unused_parameters=True to torch.nn.parallel.DistributedDataParallel; (2) making sure all forward function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to …
=> Update train.py for distributive programming

test.py, train.py
efficient calling test dataloader during training
The dataloader for test dataset is loaded every epochs during training.
I think that it can be a bottleneck in training process so I modified code.
the dataloader for test dataset is called once and after that, is not called during training.
=> efficient calling test dataloader during training

utils/torch_utils.py
Fix the conv-fuse bug when `Conv2d()` layers have `bias=True` and followed by batchnorm layers.
More details in https://github.com/ultralytics/yolov3/issues/807.
=> fusedconv bug fix

README.md
Add a link to wang-xinyu's tensorrtx/yolov3-spp in the tutorials section of the readme.
As mentioned in [issues#1000](https://github.com/ultralytics/yolov3/issues/1000)
=> Update README, add link to yolov3-spp-tensorrt

train.py
Without the attached change, I get an error displaying help:
```$ python train.py --help                                                                     
Traceback (most recent call last):
File "train.py", line 403, in <module>
opt = parser.parse_args()
File "/ascldap/users/tshead/miniconda3/lib/python3.7/argparse.py", line 1755, in parse_args
args, argv = self.parse_known_args(args, namespace)
File "/ascldap/users/tshead/miniconda3/lib/python3.7/argparse.py", line 1787, in parse_known_args
namespace, args = self._parse_known_args(args, namespace)
File "/ascldap/users/tshead/miniconda3/lib/python3.7/argparse.py", line 1993, in _parse_known_args
start_index = consume_optional(start_index)
File "/ascldap/users/tshead/miniconda3/lib/python3.7/argparse.py", line 1933, in consume_optional …
```
=> Fix argparse string escapes in train.py.

requirements.txt
In a clean environment running training fails if tensorboard is not installed e.g.
```
Traceback (most recent call last):
File "/home/josh/miniconda3/envs/ultralytics/lib/python3.7/site-packages/torch/utils/tensorboard/__init__.py", line 2, in <module>
from tensorboard.summary.writer.record_writer import RecordWriter  # noqa F401
ModuleNotFoundError: No module named 'tensorboard'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "train.py", line 6, in <module>
from torch.utils.tensorboard import SummaryWriter
File "/home/josh/miniconda3/envs/ultralytics/lib/python3.7/site-packages/torch/utils/tensorboard/__init__.py", line 4, in <module>
raise ImportError('TensorBoard logging requires TensorBoard with Python summary writer …
```
=> add tensorboard to requirements

utils/datasets.py
Faster HSV augmentation, as per https://github.com/ultralytics/yolov3/issues/1096
=> faster hsv augmentation

test.py, train.py, utils/utils.py
Per the discussion here: https://github.com/ultralytics/yolov3/issues/1096
* plots generated using OpenCV rather than Matplotlib for speed
* display object confidence and name if available
* class colours are consistent
=> faster and more informative training plots

README.md, models.py
Current behaviour when convert(...) function saves converted file always as 'converted.pt'/'converted.weights' in a root directory seems to be not intuitive and convenient.
I propose to save converted file side by side with the original one, but with new extension.
=> convert(...) changed to save target file alongside the original file

models.py
Fixing the typo in format string in the commit. Tested that now it converts without error and prints out success message.
Fix the error during weight conversion between PyTorch weights and darknet weights.
Issue #1247
=> Fixed string format error during weight conversion

models.py, utils/parse_config.py
This is a simple change, but in some of my experiments I had to add a dropout layer, and it seems like it is working. Let me know whether you think there's something missing or wrong.
I have also found that the .isnumeric() case in `parse_config.py` cannot get the float case as it looks like it was initially intended to. As I don't think this is particularly important I just left a TODO comment and manually cast to float in `models.py` for the dropout layer.
I'm not using and never used DropBlock and that's why I didn't attempt to implement it.
=> Partial support for [dropout] layer

tutorial.ipynb
The correct command for downloading coco dataset 2014 is supposed to be "!bash yolov3/data/get_coco2014.sh"
=> Modify Line 104 on getting coco dataset

utils/datasets.py
Width and height will be padding to the minimum multiple of 32 instead of 64.
=> fix padding for rectangular inference

test.py, train.py, utils/plots.py
This PR places parts of train and test plotting into daemon threads. This improves responsiveness significantly when starting new training runs, because expensive plotting tasks are run on background threads and do not prevent the main thread from starting or continuing training.
=> Daemon thread plots

utils/plots.py
This PR updates the default matplotlib backend from 'Agg' to 'svg'. This backend demonstrated the fastest canvas drawing speeds of all noninteractive backends tested. Tested plotting speeds on VOC labels.png: 'Agg' 5.4 seconds, 'svg' 2.4 seconds.
> def use(backend, *, force=True):
>     """
>     Select the backend used for rendering and GUI integration.
> 
>     Parameters
>     ----------
>     backend : str
>         The backend to switch to.  This can either be one of the standard
>         backend names, which are case-insensitive:
> 
>         - interactive backends:
>           GTK3Agg, GTK3Cairo, MacOSX, nbAgg,
>           Qt4Agg, Qt4Cairo, Qt5Agg, Qt5Cairo,
>           TkAgg, TkCairo, WebAgg, WX, WXAgg, WXCairo
> 
>         - non-interactive backends:
>           agg, cairo, pdf, …
=> Update matplotlib svg backend

models/common.py
This PR adds the default nn.Conv2d() bias to the Classify() head, fixing a minor mistake.
=> Add bias to Classify()

utils/metrics.py
This PR reinstates the precision-recall curve sentinel values modified in PR #1206 that caused issues with incorrect mAP computation at higher --conf thresholds in https://github.com/ultralytics/yolov5/issues/1466 and https://github.com/ultralytics/yolov5/issues/1622.
=> Reinstate PR curve sentinel values

test.py
This PR introduces hybrid autolabelling support in test.py. The auto-labelling options are now:
- `python test.py --save-txt`: traditional auto-labelling
- `python test.py --save-hybrid`: save hybrid autolabels, combining existing labels with new predictions before NMS (existing predictions given confidence=1.0 before NMS.
- `python test.py --save-conf`: add confidences to any of the above commands
Regardless of any of the above settings, be aware that auto-labelling works best at very high confidence thresholds, i.e. 0.90 confidence, whereas mAP computation relies on very low confidence threshold, i.e. 0.001, to properly evaluate the area under the PR curve. **The two activities are thus essentially mutually exclusive, there is no reason I know of to combine the two into a single test …
=> Hybrid auto-labelling support

utils/plots.py
This PR attempts to fix issue https://github.com/ultralytics/yolov5/issues/1623. A tolerance is introduced to the normalization determination of labels, which previously accidentally classified labels as non-normalized due to numerical precision issues.
=> Normalized mosaic plotting bug fix

hubconf.py
This PR simplifies the process of loading a custom YOLOv3/5-based model (of any architecture) in PyTorch Hub. The new syntax is very simple:
```python
import torch
model = torch.hub.load('ultralytics/yolov3', 'custom', 'path/to/custom_model.pt')
model = model.autoshape()  # for PIL/cv2/np inputs and NMS
model = torch.hub.load('ultralytics/yolov3', 'custom', custom_model)
model = model.autoshape()  # for PIL/cv2/np inputs and NMS
```
=> Simplified PyTorch Hub loading of custom models

models/yolo.py
This PR fixes Docker issue with leaf Variable inplace ops in https://github.com/ultralytics/yolov5/issues/1552.
=> leaf Variable inplace bug fix

utils/google_utils.py
This PR updates attempt_download() in google_utils.py to only query the GitHub API for missing files rather than in all cases (currently), fixing issue #1890 in YOLOv5.
All functions in this file have also been updated with Path objects now.
=> GitHub API rate limit fix

utils/general.py
Fix for `UnboundLocalError: local variable 's' referenced before assignment`.
=> check_git_status() bug fix

tutorial.ipynb
Add Kaggle Badge that allows for opening the .ipynb as a Kaggle Notebook as seen here https://www.kaggle.com/product-feedback/152480.
=> Add Open in Kaggle badge

models/experimental.py
Resolves `AttributeError: 'Upsample' object has no attribute 'recompute_scale_factor'` first raised in https://github.com/ultralytics/yolov5/issues/5499 and observed in all CI runs on just-released PyTorch 1.11.0.
=> PyTorch 1.11.0 compatibility updates

models/common.py
While running inference using YoloV3 onnx model, I got the following error :-
ValueError: This ORT build has ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'], ...)
On checking the code, in /models/common.py , after line 315, cuda = torch.cuda.is_available() was missing and also providers for onnx was missing. Hence by **referring to Onnx inference code in YoloV5 [(Yolov5/models/common.py)](https://github.com/ultralytics/yolov5/blob/master/models/common.py)**, I have added the following lines of code
```
cuda …
```
=> Fix ONNX inference code

utils/general.py
as_posix() needed so that backslashes of 'Path(file)' are output as forward slashes in the URL string (Windows, Python 3.9.12, Anaconda distribution 2022.05)
=> Fix downloading file by URL (Windows)

export.py, models/common.py, utils/downloads.py, utils/loggers/clearml/README.md, utils/loggers/clearml/clearml_utils.py, utils/loggers/comet/__init__.py, utils/loggers/comet/comet_utils.py, utils/loggers/wandb/wandb_utils.py, utils/segment/metrics.py
Thank you 🙏 for your contribution to [Ultralytics](https://ultralytics.com) 🚀! Your effort in enhancing our repositories is greatly appreciated. To streamline the process and assist us in integrating your Pull Request (PR) effectively, please follow these steps:
1. **Check for Existing Contributions**: Before submitting, kindly explore existing PRs to ensure your contribution is unique and complementary.
2. **Link Related Issues**: If your PR addresses an open issue, please link it in your submission. This helps us better understand the context and impact of your contribution.
3. **Elaborate Your Changes**: Clearly articulate the purpose of your PR. Whether it's a bug fix or a new feature, a detailed description aids in a smoother integration process.
4. **Ultralytics Contributor License …
=> Python refactor and simplification

.github/workflows/ci-testing.yml
Enhanced Python package installation process in CI testing for better stability.
- Removed the `--retries 3` option from the `pip install` command in the GitHub Actions CI testing workflow.
- **Purpose**: The change aims to streamline the installation process of Python packages, potentially making the CI (Continuous Integration) testing process more straightforward and less prone to errors caused by retry attempts.
- **Impact**: This should lead to a smoother CI testing experience, with a slight possibility that connection issues during package installation might require manual intervention more often. However, it simplifies the command, possibly making troubleshooting easier. Overall, it impacts …
=> Revert CI pip install retries to default

.github/workflows/format.yml
Improved GitHub Actions configuration for better code formatting and validation. 
- Changed the event trigger from `pull_request_target` to `pull_request`, enhancing security and workflow triggers.
- Split YAML formatting into its own setting, now handled by `prettier`, emphasizing clearer structure and dedicated processing.
- **Security & Reliability:** Switching to `pull_request` from `pull_request_target` reduces security risks and aligns with best practices, ensuring that only trusted code triggers actions in a PR.
- **Code Quality:** Separating YAML formatting with `prettier` ensures more specialized and appropriate formatting, improving readability and maintainability of configuration files.
- …
=> Add Prettier for YAML formatting to Ultralytics Actions

models/yolo.py, utils/dataloaders.py, utils/loggers/__init__.py
Enhanced code with improved documentation and minor code adjustments.
- Added docstrings to the `forward` method in the YOLO model to describe its functionality.
- Updated docstrings for label rounding in `dataloaders.py` to clarify its purpose.
- Improved documentation for the TensorBoard `SummaryWriter` import in the logger utilities.
- **Enhanced Readability**: The added and updated docstrings make the codebase easier to understand for developers, especially new contributors.
- **Improved Maintainability**: Clear documentation can aid in maintaining and extending the code.
- **Better Debugging**: Understanding each function's role helps in diagnosing issues more effectively.
=> Add missing Python function docstrings

README.md, README.zh-CN.md, tutorial.ipynb
=> Fix HUB link https://ultralytics.com/hub

classify/train.py, export.py, segment/train.py, segment/val.py, train.py, utils/__init__.py, utils/autoanchor.py, utils/downloads.py, utils/general.py, utils/loggers/comet/__init__.py, utils/plots.py, utils/segment/metrics.py, utils/torch_utils.py
=> Ultralytics Code Refactor https://ultralytics.com/actions

README.md, README.zh-CN.md
=> Fix PyPI downloads links

README.md, README.zh-CN.md, classify/predict.py, classify/train.py, detect.py, export.py, segment/predict.py, segment/train.py, train.py, utils/augmentations.py, utils/dataloaders.py, utils/general.py, utils/loggers/clearml/clearml_utils.py, utils/loggers/comet/__init__.py, utils/loggers/wandb/wandb_utils.py, utils/loss.py, utils/segment/augmentations.py, utils/segment/dataloaders.py, utils/segment/loss.py, utils/torch_utils.py
This [Ultralytics](https://ultralytics.com) PR reformats this repo with the latest improved Ruff version 0.9.0 formatter.
- [Join our Team](https://www.ultralytics.com/careers) 🌾
- [AI in Healthcare](https://www.ultralytics.com/solutions/ai-in-healthcare) 🏥
- [AI in Manufacturing](https://www.ultralytics.com/solutions/ai-in-manufacturing) 🏭
- [Attend YOLO VISION 2024](https://www.ultralytics.com/events/yolovision) 📅
<sub>Made with ❤️ …
=> Apply `ruff==0.9.0` formatting
